### ISSUE TITLE
速度围观

### ISSUE THREAD

**Issue by qiushui95** [razerdp/BasePopup-Extension#1]
😂

**Comment by qiushui95** [comment]
@razerdp 大佬  啥时候完工呢。快一年了，花儿都谢了

**Comment by razerdp** [comment]
。。。你不说我都忘了这茬了= =

**Comment by razerdp** [comment]
有个问题是。。我换了电脑，貌似找不到之前的源码了，估计得从git仓库这里的进度重新开始

**Comment by qiushui95** [comment]
> 有个问题是。。我换了电脑，貌似找不到之前的源码了，估计得从git仓库这里的进度重新开始

我刚把代码拉下来看了下  有很多文件丢失，估计你add 的时候没有add完。

**Comment by qiushui95** [comment]
> 有个问题是。。我换了电脑，貌似找不到之前的源码了，估计得从git仓库这里的进度重新开始

我期待了快一年了。。。。

**Comment by razerdp** [comment]
哈哈，没事……很多功能都是基于basepopup写的，只是封装了一下嘛…急用的话可以先自己实现←_←


我这个得回去找下看能不能恢复一下格式化的磁盘找找源码了
